name: Lint and Format with Ruff and isort

on:
  push:
    branches:
      - master

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      # Checkout the repository and fetch full history to enable pushing changes
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Python environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install necessary tools for linting and formatting
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff isort

      # Format code with Ruff
      - name: Format Code with Ruff
        run: |
          ruff format ./funcversion

      # Sort imports with isort
      - name: Sort Imports with isort
        run: |
          isort ./funcversion

      # Lint code with Ruff
      - name: Lint Code with Ruff
        run: |
          ruff check ./funcversion

      # Commit and push any formatting changes
      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./funcversion
          if ! git diff --cached --quiet; then
            git commit -m "Apply formatting changes with Ruff and isort [skip ci]"
            git push
          else
            echo "No formatting changes to commit."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
